name: Continuous Integration

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  prettier:
    timeout-minutes: 10
    name: "prettier-formatter"
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci

      - run: npx prettier . --write

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply Prettier formatting
